#!/usr/bin/env python3

# Created by: Mikayla Barthelette
# Created on: Oct 2021
# This program is the "Space Aliens" program on the PyBadge

import ugame
import stage


def game_scene():
    # this function is the main game game_scene
    
    print("\n\n\n")
    print("Hello, World!")
    
    
    while True:
        pass
    
if __name__ == "__main__":
    game_scene()
